server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location /v1/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Request-ID $request_id;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

